#!/usr/bin/env python3
"""
Build a playable episode from scratch.

Demonstrates that a fourth episode is possible: it generates a level, packs it
into group files the game can read, and leaves them where the build expects
them. The level here is deliberately plain -- the point is the pipeline, not
the level design.

    python3 tools/make-episode.py --data gamedata --episode 4

The shared assets in COSMOn.STN are identical across all three shipped
episodes, so the new episode's STN is a copy. Only the VOL is episode
specific: its maps, its title and ending screens, and whichever backdrops and
music its levels reference.
"""

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from cosmo_data import read_group, write_group, Map, SPA_PLAYER_START

# Solid tiles sampled from episode 1's own ground, so the new level is built
# from the same tile bank every episode shares.
GROUND = [0x0148, 0x0150, 0x0158]
AIR = 0x0000

# Indices into backdropNames[] and musicNames[] in game1.c.
BACKDROP_NEWSKY = 11
MUSIC_ZZTOP = 18

# Actor types taken from episode 1. 256 is its most common pickup.
ACTOR_PICKUP = 256


def build_level():
    """
    A level with ground to walk on, a staircase, and a row of pickups.

    The shape mirrors episode 1's outdoor maps: 512 wide by 63 tall, which is
    what fits the game's 64 KiB map buffer.
    """
    width, height = 512, 63
    tiles = [AIR] * (width * height)

    def put(x, y, tile):
        if 0 <= x < width and 0 <= y < height:
            tiles[y * width + x] = tile

    floor = height - 5

    # Ground across the playable stretch, with the tile varying so it does not
    # read as a repeating stamp.
    for x in range(width):
        for depth in range(4):
            put(x, floor + depth, GROUND[(x + depth) % len(GROUND)])

    # A staircase up, then a gap to jump.
    for step in range(1, 7):
        for x in range(20 + step * 3, 23 + step * 3):
            put(x, floor - step, GROUND[step % len(GROUND)])

    for x in range(52, 60):
        put(x, floor - 6, GROUND[x % len(GROUND)])

    # Two floating platforms beyond the gap.
    for x in range(66, 74):
        put(x, floor - 4, GROUND[x % len(GROUND)])
    for x in range(80, 90):
        put(x, floor - 8, GROUND[x % len(GROUND)])

    actors = [(SPA_PLAYER_START, 6, floor - 1)]
    for i in range(8):
        actors.append((ACTOR_PICKUP, 24 + i * 3, floor - i // 2 - 2))

    return Map(
        width=width,
        tiles=tiles,
        actors=actors,
        backdrop=BACKDROP_NEWSKY,
        music=MUSIC_ZZTOP,
        scroll_h=True,
    )


def write_episode_header(episode, directory):
    """
    The header that tells the game what this episode contains.

    Upstream has one of these per episode. Its feature flags select which actor
    implementations are compiled in, which is why episodes are separate
    programs rather than a runtime choice.

    MAP_NAMES alternates levels with bonus stages, matching the shape of the
    shipped episodes' tables; the game's level progression indexes into it.
    """
    os.makedirs(directory, exist_ok=True)
    path = os.path.join(directory, f"episode{episode}.h")

    levels = "\n".join(
        '    "D1.MNI",  "D1.MNI",  "bonus1.mni", "bonus2.mni", \\'
        for _ in range(8)
    ).rstrip(" \\")

    with open(path, "w") as fp:
        fp.write(f"""/*
 * Episode {episode}, generated by tools/make-episode.py.
 *
 * Not part of upstream Cosmore, which has three of these. See
 * patches/0008-allow-a-fourth-episode.patch for the one line that lets the
 * game reach it.
 */

#define END_SCREEN              "END{episode}.MNI"
#define EXIT_TEXT_PAGE          "COSMO{episode}.MNI"
#define FILENAME_BASE           "COSMO{episode}"
#define TITLE_SCREEN            "TITLE{episode}.MNI"

#define LIGHT_CAST_DISTANCE     11
#define SAVE_SLOT_INDEX         9

#define MAP_NAMES {{ \\
{levels} \\
}}

/*
 * Which optional behaviour is compiled in. Left as episode 1's, so the actors
 * this episode's levels can use are the ones episode 1 had.
 */
#define E1_CLIFFHANGER
/* #define END_GAME_CONGRATS */
/* #define EXPLOSION_PALETTE */
/* #define FOREIGN_ORDERS */
/* #define HARDER_BOSS */
#define HAS_ACT_BOSS
/* #define HAS_ACT_EXIT_MONSTER_N */
/* #define HAS_ACT_FROZEN_DN */
/* #define HAS_ACT_RED_JUMPER */
#define HAS_MAP_11
/* #define SHAREWARE */
""")
    return path


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data", default="gamedata",
                        help="directory holding the existing episodes")
    parser.add_argument("--episode", type=int, default=4)
    parser.add_argument("--source", type=int, default=1,
                        help="episode to borrow shared assets from")
    parser.add_argument("--header-dir", default="episodes",
                        help="where to write the episode header the build reads")
    args = parser.parse_args()

    source_stn = os.path.join(args.data, f"COSMO{args.source}.STN")
    source_vol = os.path.join(args.data, f"COSMO{args.source}.VOL")

    for path in (source_stn, source_vol):
        if not os.path.exists(path):
            sys.exit(f"{path} not found; the new episode borrows its assets from it")

    # The STN is byte-identical across the shipped episodes, so it is copied.
    with open(source_stn, "rb") as src:
        stn = src.read()
    target_stn = os.path.join(args.data, f"COSMO{args.episode}.STN")
    with open(target_stn, "wb") as dst:
        dst.write(stn)

    borrowed = read_group(source_vol)
    level = build_level()

    entries = {
        # One level, and a bonus stage borrowed rather than designed.
        "D1.MNI": level.to_bytes(),
        "BONUS1.MNI": borrowed["BONUS1.MNI"],
        "BONUS2.MNI": borrowed["BONUS2.MNI"],

        # Fullscreen screens. Borrowed here; a real episode would draw its own.
        f"TITLE{args.episode}.MNI": borrowed["TITLE1.MNI"],
        f"END{args.episode}.MNI": borrowed["END1.MNI"],
        f"COSMO{args.episode}.MNI": borrowed["COSMO1.MNI"],
        "PREVDEMO.MNI": borrowed["PREVDEMO.MNI"],

        # Only what the level actually asks for.
        "BDNEWSKY.MNI": borrowed["BDNEWSKY.MNI"],
        "MZZTOP.MNI": borrowed["MZZTOP.MNI"],
    }

    target_vol = os.path.join(args.data, f"COSMO{args.episode}.VOL")
    write_group(target_vol, entries)

    header = write_episode_header(args.episode, args.header_dir)

    print(f"wrote {header}")
    print(f"wrote {target_stn} ({len(stn)} bytes, copied)")
    print(f"wrote {target_vol} ({len(entries)} entries)")
    print(f"  level D1.MNI: {level.width}x{level.height}, "
          f"{len(level.actors)} actors, backdrop {level.backdrop}, "
          f"music {level.music}")


if __name__ == "__main__":
    main()
